# Glitch Project Sync workflow

name: Glitch Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '${{ secrets.PROJECTID }}'
        auth-token: 'e17dbc9b-e24b-4ee4-853e-c705b58b63c1'
